kind: Service
apiVersion: v1
metadata:
  name: msa-config-service
spec:
  type: NodePort
  selector:
    app: msa-config
  ports:
  - protocol: TCP
    port: 8888
    nodePort: 31000
    targetPort: 8888
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: msa-config
  labels:
    app: msa-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-config
  template:
    metadata:
      labels:
        app: msa-config
        version: "1.0.1"
    spec:
      containers:
      - name: msa-config
        image: docker.gsp.sicc.co.kr/cfg:1.0.1
        ports:
        - name: http
          containerPort: 8888
