apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: msa-config
  labels:
    app: msa-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa
  template:
    metadata:
      labels:
        app: msa-config
        version: "1.0.0"
    spec:
      containers:
      - name: msa-config
        image: docker.gsp.sicc.co.kr/cfg:1.0.0
        ports:
        - name: http
          containerPort: 8888
