apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: msa-config
  labels:
    app: msa-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-config
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/hostname: cfg
        pod.beta.kubernetes.io/subdomain: msa
      labels:
        app: msa-config
        version: "1.0.1"
    spec:
      hostname: cfg
      subdomain: msa
      containers:
      - name: msa-config
        image: docker.gsp.sicc.co.kr/cfg:1.0.1
        ports:
        - name: http
          containerPort: 8888