server:
  port: 8888
spring:
  application:
    name: CFG
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.org/ransang/config-repo
endpoints:
  shutdown:
    enabled: true
    sensitive: false

---
spring:
  profiles: prd
logging:
  config: classpath:logback-prd.xml
---
spring:
  profiles: ide
logging:
  config: classpath:logback-ide.xml