server:
  port: 8888
spring:
  application:
    name: CFG
  cloud:
    config:
      server:
        git:
          uri: http://git.gsp.sicc.co.kr/MSA/config-repo.git
endpoints:
  shutdown:
    enabled: true
    sensitive: false

---
spring:
  profiles: prd
logging:
  config: classpath:logback-prd.xml
---
spring:
  profiles: ide
logging:
  config: classpath:logback-ide.xml